import type { Ontogeny } from '../types'

/**
 * Caenorhabditis elegans embryonic cell lineage (hermaphrodite), after Sulston et al. 1983.
 *
 * Founder cells and their first division rounds are shown as individual nodes with the
 * standard Sulston names (AB, ABa, ABp, ABal..., EMS, MS, E, C, D, P1–P4, Z2/Z3). Beyond that,
 * each sublineage is summarised as terminal tissue nodes carrying approximate cell counts at
 * hatching (558 nuclei: AB 389, MS 80, E 20, C 47, D 20, P4 2; 671 cells generated, 113 die).
 * Times are minutes after first cleavage at 20 °C (fertilisation ≈ −50 min, hatching ≈ 800 min).
 */
export const graph: Ontogeny = {
  id: 'c-elegans',
  name: 'C. elegans embryonic lineage',
  organism: 'Caenorhabditis elegans',
  source:
    'Sulston, Schierenberg, White & Thomson 1983 Dev Biol 100:64–119 (WormAtlas edition); Maduro 2010 Dev Dyn 239:1315; Priess 2005 WormBook "Notch signaling in the C. elegans embryo"; Rose & Gönczy 2014 WormBook.',

  stages: [
    {
      id: 's0',
      label: 'P0',
      time: 0,
      description:
        'Time in minutes after first cleavage at 20 °C (Sulston et al. 1983; fertilisation ≈ −50 min). The P0 zygote is placed at 0.',
    },
    { id: 's2', label: '2-cell', time: 15, description: 'AB and P1. AB divides first (~15–18 min), P1 a couple of minutes later.' },
    { id: 's4', label: '4-cell', time: 35, description: 'ABa, ABp, EMS, P2. P2 signals ABp via APX-1/Delta → GLP-1/Notch and EMS via MOM-2/Wnt.' },
    { id: 's8', label: '8-cell', time: 50, description: 'ABal, ABar, ABpl, ABpr, MS, E, C, P3. All six founder lineages now exist (D and P4 after P3 divides).' },
    { id: 's16', label: '~16-cell', time: 75, description: '8 AB great-granddaughters plus MSa/MSp, Ea/Ep, Ca/Cp, D, P4. MS → ABalp/ABara Notch signal at the 12-cell stage.' },
    { id: 's28', label: '28-cell', time: 100, description: 'Gastrulation begins: Ea and Ep ingress from the ventral surface (100 min).' },
    { id: 's50', label: '~50-cell', time: 150, description: 'P4, MS descendants and D ingress (120–200 min); E4 stage.' },
    { id: 's100', label: 'Gastrula (~100 cells)', time: 250, description: 'Late gastrulation; AB pharyngeal precursors and C muscle precursors ingress; gastrulation cleft closes ~280–300 min.' },
    { id: 's350', label: 'Ventral enclosure', time: 350, description: 'Hypodermis spreads ventrally and seals the embryo; most embryonic divisions complete.' },
    { id: 's450', label: 'Comma', time: 450, description: 'Comma stage / onset of elongation and morphogenesis (~430–450 min). Terminal differentiation underway.' },
    { id: 's800', label: 'Hatching (L1)', time: 800, description: 'L1 hatches with 558 nuclei; postembryonic blast cells (P1–P12, seam, M, Z1–Z4) resume division after hatching.' },
  ],

  lineages: [
    { id: 'stem', label: 'Zygote & P-cell stem (P0–P3, EMS)', color: '#7f7f7f' },
    { id: 'ab', label: 'AB (ectoderm, anterior pharynx)', color: '#1f77b4' },
    { id: 'ms', label: 'MS (mesoderm, posterior pharynx)', color: '#d62728' },
    { id: 'e', label: 'E (intestine)', color: '#bcbd22' },
    { id: 'c', label: 'C (posterior hypodermis & muscle)', color: '#17becf' },
    { id: 'd', label: 'D (body muscle)', color: '#ff7f0e' },
    { id: 'germ', label: 'P4 germline', color: '#9467bd' },
  ],

  nodes: [
    // ───────────────────────── Zygote and P-cell stem series ─────────────────────────
    {
      id: 'p0',
      label: 'P0 zygote',
      parents: [],
      stage: 's0',
      lineage: 'stem',
      markers: 'pie-1 skn-1 (maternal)',
      iconId: 'cells.oocyte',
      description: 'Fertilised egg; sperm entry defines the posterior pole. PAR polarity segregates P granules and maternal determinants to the posterior.',
    },
    {
      id: 'p1',
      label: 'P1',
      parents: ['p0'],
      stage: 's2',
      markers: 'pie-1 skn-1 pal-1',
      iconId: 'cells.dividing-cell',
      description: 'Smaller posterior daughter; stem-like, cleaves unequally for three more rounds (P2, P3, P4).',
    },
    {
      id: 'ems',
      label: 'EMS',
      parents: ['p1'],
      stage: 's4',
      markers: 'skn-1 med-1/2 pop-1',
      iconId: 'cells.dividing-cell',
      description: 'Anterior daughter of P1. SKN-1 activates med-1/2; MOM-2/Wnt from P2 polarises EMS so the posterior daughter (E) has low nuclear POP-1 and becomes endoderm.',
    },
    {
      id: 'p2',
      label: 'P2',
      parents: ['p1'],
      stage: 's4',
      markers: 'pie-1 pal-1 apx-1 mom-2',
      iconId: 'cells.dividing-cell',
      description: 'Posterior daughter of P1; signalling centre at the 4-cell stage (APX-1/Delta → ABp Notch; MOM-2/Wnt → EMS). PIE-1 represses somatic transcription.',
    },
    {
      id: 'p3',
      label: 'P3',
      parents: ['p2'],
      stage: 's8',
      markers: 'pie-1 pal-1',
      iconId: 'cells.dividing-cell',
      description: 'Divides unequally into D (anterior, somatic) and P4 (posterior, germline).',
    },

    // ───────────────────────── AB lineage (389 cells at hatching) ─────────────────────────
    {
      id: 'ab',
      label: 'AB',
      parents: ['p0'],
      stage: 's2',
      lineage: 'ab',
      markers: 'glp-1 pop-1',
      iconId: 'cells.dividing-cell',
      description: 'Larger anterior daughter of P0; divides equally with a ~15 min period. Gives 389 of the 558 cells at hatching (214 neurons, ~40 glia/support cells, 72 hypodermal cells, anterior pharynx and arcade, excretory system, rectum, 1 body muscle).',
    },
    {
      id: 'aba',
      label: 'ABa',
      parents: ['ab'],
      stage: 's4',
      markers: 'tbx-37/38 ref-1',
      iconId: 'cells.dividing-cell',
      description: 'Anterior daughter of AB; not contacted by P2, so no Notch at the 4-cell stage. Its descendants ABalp and ABara receive Notch from MS at the 12-cell stage and form anterior pharynx.',
    },
    {
      id: 'abp',
      label: 'ABp',
      parents: ['ab'],
      stage: 's4',
      markers: 'glp-1 (Notch, via APX-1) ref-1',
      iconId: 'cells.dividing-cell',
      description: 'Posterior daughter of AB; contacts P2 and receives APX-1 → GLP-1/Notch, which distinguishes it from ABa (makes no pharynx; ventral/posterior ectoderm, excretory cell, rectum).',
    },
    { id: 'abal', label: 'ABal', parents: ['aba'], stage: 's8', iconId: 'cells.dividing-cell', description: 'Left anterior AB granddaughter: head neurons and glia; ABalp forms anterior pharynx after MS Notch signal.' },
    { id: 'abar', label: 'ABar', parents: ['aba'], stage: 's8', iconId: 'cells.dividing-cell', description: 'Right anterior AB granddaughter: ABara → anterior pharynx; ABarp → anterior/dorsal hypodermis, seam cells and neurons.' },
    { id: 'abpl', label: 'ABpl', parents: ['abp'], stage: 's8', iconId: 'cells.dividing-cell', description: 'Left posterior AB granddaughter: ventral hypodermis and P blast cells, neurons, excretory cell and duct, rectal cells.' },
    { id: 'abpr', label: 'ABpr', parents: ['abp'], stage: 's8', iconId: 'cells.dividing-cell', description: 'Right posterior AB granddaughter: largely the mirror image of ABpl; also the single AB body muscle (ABprpppppaa) and G1 pore cell.' },

    { id: 'abala', label: 'ABala', parents: ['abal'], stage: 's16', iconId: 'cells.dividing-cell', description: 'Mostly head neurons and glia (ring ganglia, amphid sheath/socket).' },
    { id: 'abalp', label: 'ABalp', parents: ['abal'], stage: 's16', markers: 'pha-4 (after MS Notch)', iconId: 'cells.dividing-cell', description: 'Receives LAG-2/Notch from MS at the 12-cell stage → anterior pharynx (left), plus some neurons.' },
    { id: 'abara', label: 'ABara', parents: ['abar'], stage: 's16', markers: 'pha-4 (after MS Notch)', iconId: 'cells.dividing-cell', description: 'Receives Notch from MS → anterior pharynx (right), arcade cells, some neurons.' },
    { id: 'abarp', label: 'ABarp', parents: ['abar'], stage: 's16', markers: 'elt-1 lin-26', iconId: 'cells.dividing-cell', description: 'Mostly hypodermis (hyp4–hyp7 dorsal, head seam cells H0–H2, V1–V2) and some neurons.' },
    { id: 'abpla', label: 'ABpla', parents: ['abpl'], stage: 's16', iconId: 'cells.dividing-cell', description: 'Ventral/lateral hypodermis, left P blast cells, seam cells (V3–V6), neurons.' },
    { id: 'abplp', label: 'ABplp', parents: ['abpl'], stage: 's16', iconId: 'cells.dividing-cell', description: 'Ventral cord and tail neurons, excretory cell (ABplpappaap) and duct (ABplpaaaapa), rectal cells, hyp7/hyp10.' },
    { id: 'abpra', label: 'ABpra', parents: ['abpr'], stage: 's16', iconId: 'cells.dividing-cell', description: 'Mirror of ABpla: ventral/lateral hypodermis, right P blast cells, seam cells, neurons.' },
    { id: 'abprp', label: 'ABprp', parents: ['abpr'], stage: 's16', iconId: 'cells.dividing-cell', description: 'Neurons, G1 excretory pore (ABprpaaaapa), rectal cells (B, Y, U), preanal muscles incl. the single AB body muscle (ABprpppppaa).' },

    {
      id: 'ab-pharynx-ant',
      label: 'Anterior pharynx (AB)',
      parents: ['abalp', 'abara'],
      stage: 's450',
      markers: 'pha-4 ceh-22',
      terminal: true,
      description: 'Anterior pharyngeal muscles, marginal, epithelial, gland cells and pharyngeal neurons derived from ABalp and ABara after the MS Notch signal; together with arcade cells ~ half of the ~80-cell pharynx. The remainder comes from MS.',
    },
    {
      id: 'ab-neurons-head',
      label: 'Head neurons & glia (ABa)',
      parents: ['abala', 'abarp', 'abalp'],
      stage: 's450',
      markers: 'unc-119 rab-3 unc-86',
      iconId: 'cells.neuron',
      terminal: true,
      description: 'Anterior sensory neurons (amphids, cephalic, labial sensilla), ring interneurons and their sheath/socket glia. AB produces 214 of the 222 neurons present at hatching and all sensillar support cells.',
    },
    {
      id: 'ab-neurons-vent',
      label: 'Ventral cord & tail neurons (ABp)',
      parents: ['abplp', 'abprp', 'abpla', 'abpra'],
      stage: 's450',
      markers: 'unc-4 unc-30 (motor neuron classes)',
      iconId: 'cells.neuron',
      terminal: true,
      description: 'Embryonic ventral cord motor neurons (DA, DB, DD), retrovesicular and preanal/lumbar ganglion neurons, tail sensory neurons (PHA/PHB) and glia.',
    },
    {
      id: 'ab-hypodermis',
      label: 'Hypodermis hyp1–hyp11 (AB, ~40)',
      parents: ['abarp', 'abpla', 'abpra', 'abplp', 'abprp'],
      stage: 's350',
      markers: 'elt-1 lin-26 dpy-7',
      iconId: 'cells.epithelial-sheet',
      terminal: true,
      description: 'Mononucleate hypodermal cells that fuse into the syncytia hyp1–hyp7 (anterior/dorsal/ventral hyp7) and tail hyp8–hyp11, plus arcade cells. With seam and P cells, AB contributes 72 hypodermal cells; C adds 13 dorsal hyp7 nuclei.',
    },
    {
      id: 'ab-seam',
      label: 'Seam cells H0–H2, V1–V6, T (20)',
      parents: ['abarp', 'abpla', 'abpra'],
      stage: 's800',
      markers: 'elt-1 egl-18 ceh-16',
      iconId: 'cells.epithelial-sheet',
      description: 'Lateral hypodermal blast cells (10 per side) that divide stem-cell-like through larval life and form alae.',
    },
    {
      id: 'ab-pblast',
      label: 'Ventral P blast cells (P1–P12)',
      parents: ['abpla', 'abpra'],
      stage: 's800',
      markers: 'lin-39 mab-5 (Hox)',
      description: 'Twelve ventral hypodermal blast cells (6 per side) born from ABpla/ABpra; in L1 they generate ventral cord neurons and hypodermis (Pn.a / Pn.p; P5–P7.p form the vulva).',
    },
    {
      id: 'ab-excretory',
      label: 'Excretory canal cell',
      parents: ['abplp'],
      stage: 's450',
      markers: 'ceh-6 pros-1',
      terminal: true,
      description: 'ABplpappaap: single large H-shaped osmoregulatory cell; its mother divides at ~270 min. Excretory gland cells derive from the same ABplp/ABprp region.',
    },
    {
      id: 'ab-exc-duct-pore',
      label: 'Excretory duct & G1 pore',
      parents: ['abplp', 'abprp'],
      stage: 's450',
      markers: 'lin-48',
      terminal: true,
      description: 'Duct cell ABplpaaaapa and socket/pore cell G1 ABprpaaaapa; a regulative equivalence pair.',
    },
    {
      id: 'ab-rectum',
      label: 'Rectum & rectal gland',
      parents: ['abplp', 'abprp'],
      stage: 's450',
      markers: 'egl-5 mab-9',
      terminal: true,
      description: 'Rectal epithelial cells B, F, K, K\', U, Y, three rectal gland cells and the intestino-rectal valve (virL/R); sink into the ventral tail late in gastrulation.',
    },
    {
      id: 'ab-muscle',
      label: 'Body wall muscle (AB, 1 cell)',
      parents: ['abprp'],
      stage: 's450',
      markers: 'hlh-1 unc-120',
      iconId: 'cells.skeletal-muscle-fiber',
      terminal: true,
      description: 'ABprpppppaa, the only AB-derived body muscle (its left homologue becomes the sphincter muscle). Part of a preanal group of four AB muscles with the anal depressor, sphincter and one intestinal muscle; mothers divide at 295 min.',
    },

    // ───────────────────────── MS lineage (80 cells at hatching) ─────────────────────────
    {
      id: 'ms',
      label: 'MS',
      parents: ['ems'],
      stage: 's8',
      lineage: 'ms',
      markers: 'tbx-35 ceh-51 pop-1 (high)',
      iconId: 'cells.dividing-cell',
      description: 'Anterior daughter of EMS (high nuclear POP-1). MED-1/2 → tbx-35/ceh-51. Gives 80 cells: posterior pharynx (~37), 28 body muscles, 4 coelomocytes, Z1/Z4, hmc, M, mu int R, 6 neurons. Also sends LAG-2/Notch to ABalp/ABara at the 12-cell stage.',
    },
    { id: 'msa', label: 'MSa', parents: ['ms'], stage: 's16', iconId: 'cells.dividing-cell', description: 'Anterior MS daughter: MSaa/MSap → mostly pharynx and body muscle; MSap also gives Z4, M mesoblast and coelomocytes.' },
    { id: 'msp', label: 'MSp', parents: ['ms'], stage: 's16', iconId: 'cells.dividing-cell', description: 'Posterior MS daughter: pharynx, body muscle, Z1, hmc, mu int R and coelomocytes. MS8 cells ingress at 120–200 min.' },
    {
      id: 'ms-pharynx',
      label: 'Posterior pharynx (MS, ~37)',
      parents: ['msa', 'msp'],
      stage: 's450',
      markers: 'pha-4 ceh-22 myo-2',
      terminal: true,
      description: 'Posterior pharyngeal muscles (m3–m8), marginal and gland cells, pharyngeal neurons and pharyngo-intestinal valve, derived from MSaa and MSpa.',
    },
    {
      id: 'ms-muscle',
      label: 'Body wall muscle (MS, 28)',
      parents: ['msa', 'msp'],
      stage: 's450',
      markers: 'hlh-1 unc-120 myo-3',
      iconId: 'cells.skeletal-muscle-fiber',
      terminal: true,
      description: 'Anterior body wall muscles, 14 per side, generated symmetrically by MSap/MSpp and MSaa/MSpa branches. Of 81 L1 body muscles, 80 arise symmetrically from MS, C and D.',
    },
    {
      id: 'ms-coelomocytes',
      label: 'Coelomocytes (4)',
      parents: ['msa', 'msp'],
      stage: 's450',
      markers: 'cup-4 unc-122',
      terminal: true,
      description: 'Four embryonic coelomocytes (ccAL/R, ccPL/R) generated symmetrically; scavenger cells of the pseudocoelom.',
    },
    {
      id: 'ms-hmc',
      label: 'Head mesodermal cell (hmc)',
      parents: ['msp'],
      stage: 's450',
      terminal: true,
      description: 'Dorsal midline mesodermal cell; one of a homologous pair (sisters of the somatic gonad precursors) of which the anterior one dies late in embryogenesis.',
    },
    {
      id: 'ms-m',
      label: 'M mesoblast (MSapaapp)',
      parents: ['msa'],
      stage: 's800',
      markers: 'hlh-8 hlh-1',
      description: 'Postembryonic mesoblast, born on the left next to the pharynx and migrating posteriorly between Z2/Z3; in larvae gives body muscles, coelomocytes and sex muscles. Its contralateral homologue becomes the right intestinal muscle (mu int R).',
    },
    {
      id: 'ms-z1z4',
      label: 'Somatic gonad precursors (Z1, Z4)',
      parents: ['msp', 'msa'],
      stage: 's800',
      markers: 'hnd-1 ehn-3 ceh-34',
      description: 'Z1 (MSpppaap) and Z4 (MSappaap), bilateral homologues that flank Z2/Z3 in the L1 gonad primordium and generate the entire somatic gonad postembryonically.',
    },

    // ───────────────────────── E lineage (intestine, 20 cells) ─────────────────────────
    {
      id: 'e',
      label: 'E',
      parents: ['ems'],
      stage: 's8',
      lineage: 'e',
      markers: 'end-1 end-3 pop-1 (low)',
      iconId: 'cells.dividing-cell',
      description: 'Posterior daughter of EMS, specified by Wnt/MOM-2 from P2 (low nuclear POP-1) plus SKN-1 → MED-1/2 → END-1/END-3. Clonally produces the whole intestine (20, occasionally 21–22 cells).',
    },
    { id: 'e2', label: 'E2 (Ea, Ep)', parents: ['e'], stage: 's16', markers: 'end-1 end-3 elt-7', iconId: 'cells.dividing-cell', description: 'Ea and Ep are the first cells to ingress, at 100 min (28-cell stage), initiating gastrulation.' },
    { id: 'e4', label: 'E4', parents: ['e2'], stage: 's50', markers: 'elt-2 elt-7', iconId: 'cells.dividing-cell', description: 'Four intestinal precursors inside the embryo; ELT-2 now drives all subsequent gut differentiation.' },
    { id: 'e8', label: 'E8', parents: ['e4'], stage: 's100', markers: 'elt-2', iconId: 'cells.dividing-cell', description: 'Eight E cells form a two-row primordium along the body axis.' },
    { id: 'e16', label: 'E16', parents: ['e8'], stage: 's350', markers: 'elt-2 ges-1', iconId: 'cells.dividing-cell', description: '16 cells arranged as a cylinder with a lumen; intestinal rings int1–int9 begin to form.' },
    {
      id: 'intestine',
      label: 'Intestine (20 cells)',
      parents: ['e16'],
      stage: 's450',
      markers: 'elt-2 ges-1 ifb-2',
      iconId: 'tissues.intestine',
      terminal: true,
      description: 'Final E16 → E20 division of four cells gives 20 polarised epithelial cells in 9 rings (int1 has 4 cells); nuclei become polyploid postembryonically.',
    },

    // ───────────────────────── C lineage (47 cells at hatching) ─────────────────────────
    {
      id: 'c',
      label: 'C',
      parents: ['p2'],
      stage: 's8',
      lineage: 'c',
      markers: 'pal-1 tbx-8/9',
      iconId: 'cells.dividing-cell',
      description: 'Anterior daughter of P2; specified by PAL-1 (Caudal). Gives 47 cells: 32 body muscles, 13 dorsal/posterior hypodermal cells and 2 neurons.',
    },
    { id: 'ca', label: 'Ca', parents: ['c'], stage: 's16', iconId: 'cells.dividing-cell', description: 'Caa → hypodermis (and neuron DVC); Cap → body muscle. Anterior/posterior fates resolved by POP-1 asymmetry.' },
    { id: 'cp', label: 'Cp', parents: ['c'], stage: 's16', iconId: 'cells.dividing-cell', description: 'Cpa → hypodermis (and neuron PVR); Cpp → body muscle. C muscle precursors travel ventrally and ingress just after D.' },
    {
      id: 'c-hypodermis',
      label: 'Dorsal hypodermis (C, 13)',
      parents: ['ca', 'cp'],
      stage: 's350',
      markers: 'elt-1 lin-26',
      iconId: 'cells.epithelial-sheet',
      terminal: true,
      description: 'Dorsal hyp7 nuclei over the posterior two-thirds of the body (Caa, Cpa); born subdorsally in two rows and intercalate by contralateral nuclear migration.',
    },
    {
      id: 'c-muscle',
      label: 'Body wall muscle (C, 32)',
      parents: ['ca', 'cp'],
      stage: 's450',
      markers: 'hlh-1 unc-120 vab-7',
      iconId: 'cells.skeletal-muscle-fiber',
      terminal: true,
      description: 'Posterior body wall muscles from Cap and Cpp (16 per side).',
    },
    {
      id: 'c-neurons',
      label: 'Neurons DVC & PVR (C, 2)',
      parents: ['ca', 'cp'],
      stage: 's450',
      iconId: 'cells.neuron',
      terminal: true,
      description: 'DVC (Caaapp) and PVR (Cpaapp), the only neurons not derived from AB or MS.',
    },

    // ───────────────────────── D lineage (20 body muscles) ─────────────────────────
    {
      id: 'd',
      label: 'D',
      parents: ['p3'],
      stage: 's16',
      lineage: 'd',
      markers: 'pal-1 hlh-1',
      iconId: 'cells.dividing-cell',
      description: 'Anterior daughter of P3; generates only body muscle (clonal). Enters the interior after dividing to four cells, with MS(a/p)p.',
    },
    {
      id: 'd-muscle',
      label: 'Body wall muscle (D, 20)',
      parents: ['d'],
      stage: 's450',
      markers: 'hlh-1 unc-120 myo-3',
      iconId: 'cells.skeletal-muscle-fiber',
      terminal: true,
      description: 'Twenty posterior/central body wall muscles, 10 per side.',
    },

    // ───────────────────────── P4 germline ─────────────────────────
    {
      id: 'p4',
      label: 'P4',
      parents: ['p3'],
      stage: 's16',
      lineage: 'germ',
      markers: 'pie-1 pgl-1 nos-2',
      iconId: 'cells.dividing-cell',
      description: 'Germline founder; inherits all P granules, transcriptionally quiescent (PIE-1). Ingresses after Ea/Ep (120–200 min) and divides once in the embryo.',
    },
    {
      id: 'z2',
      label: 'Z2 primordial germ cell',
      parents: ['p4'],
      stage: 's100',
      markers: 'pgl-1 glh-1 nos-2',
      description: 'One of the two primordial germ cells; extends lobes into the intestine, arrests until L1 feeding, then proliferates to form the germline.',
    },
    {
      id: 'z3',
      label: 'Z3 primordial germ cell',
      parents: ['p4'],
      stage: 's100',
      markers: 'pgl-1 glh-1 nos-2',
      description: 'Sister of Z2; together with Z1/Z4 forms the four-cell L1 gonad primordium.',
    },
  ],

  edges: [
    { from: 'ab', to: 'abp', label: 'Notch (APX-1 from P2)' },
    { from: 'ems', to: 'ms', label: 'POP-1 high' },
    { from: 'ems', to: 'e', label: 'Wnt (MOM-2 from P2), POP-1 low' },
    { from: 'abalp', to: 'ab-pharynx-ant', label: 'Notch (LAG-2 from MS)' },
    { from: 'p3', to: 'p4', label: 'P granules, PIE-1' },
  ],
}
