import type { Ontogeny } from '../types'

/**
 * Adult haematopoiesis (human / mouse).
 *
 * The primary tree follows the classical Weissman/Akashi–Kondo hierarchy:
 * LT-HSC → ST-HSC → MPP → CMP / CLP → GMP / MEP → lineage-committed progenitors →
 * precursors → mature blood and immune cells. Well-established revisions are added as
 * SECONDARY parents (drawn dashed): MPP → LMPP → GMP / CLP (Adolfsson 2005; Doulatov 2010),
 * the megakaryocyte-biased MPP2 → MEP / MkP shortcut (Pietras 2015; Sanjuan-Pla 2013),
 * a lymphoid contribution to pDC (Rodrigues 2018; Dress 2019), thymic seeding by LMPP-like
 * cells, and GC-independent memory B / extrafollicular plasma cells.
 *
 * Stages are hierarchy TIERS, not developmental time: `time` is the tier index.
 * Surface markers are human (CD) unless noted; mouse equivalents noted where they differ.
 */
export const graph: Ontogeny = {
  id: 'hematopoiesis',
  name: 'Hematopoiesis',
  organism: 'Human / mouse',
  source:
    'Doulatov, Notta, Laurenti & Dick 2012 Cell Stem Cell; Seita & Weissman 2010 WIREs Syst Biol Med; Pietras et al. 2015 Cell Stem Cell; Notta et al. 2016 Science; Laurenti & Göttgens 2018 Nature; Görgens et al. 2013 Cell Rep; Collin & Bigley 2018 Immunology; Vivier et al. 2018 Cell.',

  // Time = hierarchy tier (0 = stem), not days.
  stages: [
    { id: 'stem', label: 'Stem', time: 0, description: 'Hierarchy tier 0. Time is a hierarchy level (tier index), not days or weeks.' },
    { id: 'multipotent', label: 'Multipotent', time: 1, description: 'Tier 1: multipotent progenitors with little or no self-renewal.' },
    { id: 'oligopotent', label: 'Oligopotent', time: 2, description: 'Tier 2: oligopotent progenitors (CMP, CLP, GMP, MEP).' },
    { id: 'committed', label: 'Lineage-committed', time: 3, description: 'Tier 3: unilineage (or bilineage) committed progenitors.' },
    { id: 'precursor', label: 'Precursor', time: 4, description: 'Tier 4: morphologically recognisable precursors / maturing cells.' },
    { id: 'mature', label: 'Mature', time: 5, description: 'Tier 5: mature circulating or tissue-resident cells.' },
  ],

  lineages: [
    { id: 'hspc', label: 'HSPC', color: '#7f7f7f' },
    { id: 'erythroid', label: 'Erythroid', color: '#d62728' },
    { id: 'megakaryocytic', label: 'Megakaryocytic', color: '#ff7f0e' },
    { id: 'granulocytic', label: 'Granulocytic', color: '#bcbd22' },
    { id: 'monocytic', label: 'Monocytic', color: '#8c564b' },
    { id: 'dendritic', label: 'Dendritic', color: '#e377c2' },
    { id: 'b-lymphoid', label: 'B lymphoid', color: '#1f77b4' },
    { id: 't-lymphoid', label: 'T lymphoid', color: '#9467bd' },
    { id: 'nk-ilc', label: 'NK / ILC', color: '#17becf' },
  ],

  nodes: [
    // ───────────────────────── Stem & multipotent compartment (HSPC) ─────────────────────────
    {
      id: 'lt-hsc',
      label: 'Long-term HSC (LT-HSC)',
      parents: [],
      stage: 'stem',
      lineage: 'hspc',
      markers: 'CD34+ CD38− CD90+ CD45RA− CD49f+',
      iconId: 'cells.generic-cell',
      description: 'Self-renewing, quiescent stem cell with lifelong multilineage repopulation. Mouse: Lin− Sca1+ Kit+ CD150+ CD48− CD34− Flt3−.',
    },
    {
      id: 'st-hsc',
      label: 'Short-term HSC (ST-HSC)',
      parents: ['lt-hsc'],
      stage: 'stem',
      markers: 'CD34+ CD38− CD90− CD49f−',
      description: 'Limited self-renewal; transient multilineage repopulation (weeks–months). Mouse: LSK CD150+ CD48− CD34+ Flt3−.',
    },
    {
      id: 'mpp',
      label: 'Multipotent progenitor (MPP)',
      parents: ['st-hsc'],
      stage: 'multipotent',
      markers: 'CD34+ CD38− CD90− CD45RA−',
      description: 'Multipotent, no durable self-renewal. Mouse MPP subsets (MPP2/3/4) are lineage-biased (Pietras 2015).',
    },
    {
      id: 'lmpp',
      label: 'Lymphoid-primed MPP (LMPP)',
      parents: ['mpp'],
      stage: 'multipotent',
      markers: 'CD34+ CD38− CD45RA+ FLT3hi',
      description: 'Lymphoid-primed multipotent progenitor retaining granulocyte–monocyte but lacking Mk/E potential (Adolfsson 2005; Doulatov 2010). Mouse: LSK Flt3hi (MPP4).',
    },
    {
      id: 'mpp2',
      label: 'Megakaryocyte-biased MPP (MPP2)',
      parents: ['mpp'],
      stage: 'multipotent',
      markers: 'FLT3− CD150+ CD48+ VWF',
      description: 'Mouse MPP2 (and vWF+ platelet-biased HSC) with megakaryocyte/erythroid bias; feeds MEP and MkP directly, bypassing CMP (Pietras 2015; Sanjuan-Pla 2013).',
    },

    // ───────────────────────── Oligopotent progenitors ─────────────────────────
    {
      id: 'cmp',
      label: 'Common myeloid progenitor (CMP)',
      parents: ['mpp'],
      stage: 'oligopotent',
      markers: 'CD34+ CD38+ CD123+ CD45RA−',
      description: 'Myelo-erythroid oligopotent progenitor (Akashi 2000; Manz 2002). Mouse: Lin− Kit+ Sca1− CD34+ FcγRlo. Largely bypassed in adult human marrow per Notta 2016.',
    },
    {
      id: 'clp',
      label: 'Common lymphoid progenitor (CLP)',
      parents: ['mpp', 'lmpp'],
      stage: 'oligopotent',
      markers: 'CD34+ CD38+ CD10+ CD45RA+ IL7R+',
      description: 'B, T, NK, ILC and (partly) pDC potential (Kondo 1997; Galy 1995). Mouse: Lin− IL7Rα+ Flt3+ Kitlo Sca1lo. Secondary parent: LMPP.',
    },
    {
      id: 'gmp',
      label: 'Granulocyte–monocyte progenitor (GMP)',
      parents: ['cmp', 'lmpp'],
      stage: 'oligopotent',
      markers: 'CD34+ CD38+ CD123+ CD45RA+',
      description: 'Granulocyte, monocyte, DC and mast-cell potential. Mouse: Lin− Kit+ Sca1− CD34+ FcγRhi. Secondary parent: LMPP (revised model).',
    },
    {
      id: 'mep',
      label: 'Megakaryocyte–erythroid progenitor (MEP)',
      parents: ['cmp', 'mpp2'],
      stage: 'oligopotent',
      markers: 'CD34+ CD38+ CD123− CD45RA−',
      description: 'Bipotent Mk/E progenitor. Mouse: Lin− Kit+ Sca1− CD34− FcγRlo. Secondary parent: Mk-biased MPP2.',
    },

    // ───────────────────────── Erythroid ─────────────────────────
    {
      id: 'bfu-e',
      label: 'Burst-forming unit–erythroid (BFU-E)',
      parents: ['mep'],
      stage: 'committed',
      lineage: 'erythroid',
      markers: 'CD34+ CD36− KIT+ EPORlo',
      description: 'Earliest erythroid-committed progenitor; SCF-dependent, EPO-independent.',
    },
    {
      id: 'cfu-e',
      label: 'Colony-forming unit–erythroid (CFU-E)',
      parents: ['bfu-e'],
      stage: 'committed',
      markers: 'CD34− CD36+ CD71+ EPORhi',
      description: 'EPO-dependent late erythroid progenitor; GATA1 KLF1.',
    },
    {
      id: 'proerythroblast',
      label: 'Proerythroblast',
      parents: ['cfu-e'],
      stage: 'precursor',
      markers: 'CD71hi CD235alo GATA1',
      description: 'First morphologically recognisable erythroid precursor.',
    },
    {
      id: 'erythroblast',
      label: 'Erythroblast (baso → ortho)',
      parents: ['proerythroblast'],
      stage: 'precursor',
      markers: 'CD71+ CD235a+ HBB',
      description: 'Basophilic → polychromatic → orthochromatic erythroblast; haemoglobin accumulation and nuclear condensation.',
    },
    {
      id: 'reticulocyte',
      label: 'Reticulocyte',
      parents: ['erythroblast'],
      stage: 'precursor',
      markers: 'CD71lo CD235a+ enucleated',
      description: 'Enucleated; residual RNA/ribosomes; matures in blood over ~1–2 days.',
    },
    {
      id: 'erythrocyte',
      label: 'Erythrocyte (RBC)',
      parents: ['reticulocyte'],
      stage: 'mature',
      terminal: true,
      iconId: 'cells.red-blood-cell',
      markers: 'CD235a+ CD71− HBA HBB',
      description: 'Mature red blood cell; lifespan ~120 days (human).',
    },

    // ───────────────────────── Megakaryocytic ─────────────────────────
    {
      id: 'mkp',
      label: 'Megakaryocyte progenitor (MkP)',
      parents: ['mep', 'mpp2'],
      stage: 'committed',
      lineage: 'megakaryocytic',
      markers: 'CD34+ CD41a+ CD42b− KIT+',
      description: 'Unilineage Mk progenitor. Also arises directly from Mk-biased MPP2 / vWF+ HSC (secondary parent), bypassing MEP.',
    },
    {
      id: 'megakaryoblast',
      label: 'Megakaryoblast',
      parents: ['mkp'],
      stage: 'precursor',
      markers: 'CD41+ CD61+ CD42blo',
      description: 'TPO/MPL-driven; begins endomitosis.',
    },
    {
      id: 'megakaryocyte',
      label: 'Megakaryocyte',
      parents: ['megakaryoblast'],
      stage: 'precursor',
      markers: 'CD41+ CD42b+ CD61+ polyploid',
      description: 'Polyploid (up to 64N) cell extending proplatelets into marrow sinusoids.',
    },
    {
      id: 'platelet',
      label: 'Platelet',
      parents: ['megakaryocyte'],
      stage: 'mature',
      terminal: true,
      iconId: 'cells.platelet',
      markers: 'CD41+ CD42b+ CD61+ anucleate',
      description: 'Anucleate cytoplasmic fragment; lifespan ~7–10 days.',
    },

    // ───────────────────────── Granulocytic (neutrophil, eosinophil, basophil, mast cell) ─────────────────────────
    {
      id: 'myeloblast',
      label: 'Myeloblast',
      parents: ['gmp'],
      stage: 'committed',
      lineage: 'granulocytic',
      markers: 'CD34+ CD117+ CD13+ MPO+',
      description: 'Earliest neutrophil-lineage precursor; CEBPA-dependent.',
    },
    {
      id: 'promyelocyte',
      label: 'Promyelocyte',
      parents: ['myeloblast'],
      stage: 'precursor',
      markers: 'CD13+ CD33+ MPO+ CD15lo',
      description: 'Primary (azurophilic) granule formation; MPO, ELANE.',
    },
    {
      id: 'myelocyte',
      label: 'Myelocyte',
      parents: ['promyelocyte'],
      stage: 'precursor',
      markers: 'CD15+ CD11b+ LTF+ CD16−',
      description: 'Secondary (specific) granule formation; last proliferating stage; CEBPE.',
    },
    {
      id: 'band-neutrophil',
      label: 'Metamyelocyte / band neutrophil',
      parents: ['myelocyte'],
      stage: 'precursor',
      markers: 'CD15+ CD11b+ CD16lo',
      description: 'Post-mitotic; nuclear indentation; tertiary granules.',
    },
    {
      id: 'neutrophil',
      label: 'Neutrophil',
      parents: ['band-neutrophil'],
      stage: 'mature',
      terminal: true,
      iconId: 'cells.neutrophil',
      markers: 'CD15+ CD16+ CD66b+',
      description: 'Segmented polymorphonuclear phagocyte; most abundant leukocyte. Mouse: Ly6G+ CD11b+.',
    },
    {
      id: 'eop',
      label: 'Eosinophil progenitor (EoP)',
      parents: ['gmp'],
      stage: 'committed',
      markers: 'CD34+ CD125 (IL5RA)+ GATA1',
      description: 'Unilineage eosinophil progenitor (Mori 2009; Iwasaki 2005).',
    },
    {
      id: 'eosinophil',
      label: 'Eosinophil',
      parents: ['eop'],
      stage: 'mature',
      terminal: true,
      markers: 'CCR3+ Siglec-8+ CD125+ EPX',
      description: 'Bilobed nucleus, eosinophilic crystalloid granules (MBP, EPX). Mouse: Siglec-F+.',
    },
    {
      id: 'bap',
      label: 'Basophil progenitor (BaP)',
      parents: ['gmp'],
      stage: 'committed',
      markers: 'CD34+ CD123+ FcεRIlo GATA2',
      description: 'In mouse, basophils and mast cells share a bipotent BMCP (Arinobu 2005); simplified here as separate committed progenitors.',
    },
    {
      id: 'basophil',
      label: 'Basophil',
      parents: ['bap'],
      stage: 'mature',
      terminal: true,
      markers: 'FcεRI+ CD123+ CD203c+',
      description: 'Circulating granulocyte; histamine and IL-4 release.',
    },
    {
      id: 'mcp',
      label: 'Mast cell progenitor (MCP)',
      parents: ['gmp', 'mpp'],
      stage: 'committed',
      markers: 'CD34+ CD117+ FcεRI+ CD13+',
      description: 'Circulating committed progenitor that completes maturation in tissue. Secondary parent: direct MPP origin reported in mouse (Chen 2005).',
    },
    {
      id: 'mast-cell',
      label: 'Mast cell',
      parents: ['mcp'],
      stage: 'mature',
      terminal: true,
      markers: 'CD117 (KIT)+ FcεRI+ TPSAB1',
      description: 'Tissue-resident; long-lived; SCF-dependent; tryptase/chymase granules.',
    },

    // ───────────────────────── Monocytic ─────────────────────────
    {
      id: 'mdp',
      label: 'Monocyte–DC progenitor (MDP)',
      parents: ['gmp'],
      stage: 'committed',
      lineage: 'monocytic',
      markers: 'CD34+ CD115+ CD135+ CD116+',
      description: 'Bipotent monocyte / dendritic-cell progenitor (Fogg 2006; Lee 2015 human).',
    },
    {
      id: 'cmop',
      label: 'Common monocyte progenitor (cMoP)',
      parents: ['mdp'],
      stage: 'committed',
      markers: 'CD117+ CD64+ CD115+ CD135−',
      description: 'Monocyte-restricted progenitor (Hettinger 2013; Kawamura 2017 human).',
    },
    {
      id: 'promonocyte',
      label: 'Promonocyte',
      parents: ['cmop'],
      stage: 'precursor',
      markers: 'CD64+ CD115+ CD14lo',
      description: 'Pre-monocyte in marrow; IRF8 KLF4.',
    },
    {
      id: 'monocyte',
      label: 'Classical monocyte',
      parents: ['promonocyte'],
      stage: 'mature',
      markers: 'CD14+ CD16− CCR2+ CD115+',
      description: 'Circulating classical monocyte (mouse Ly6Chi); gives rise to non-classical monocytes, monocyte-derived macrophages, moDC and osteoclasts.',
    },
    {
      id: 'nonclassical-monocyte',
      label: 'Nonclassical monocyte',
      parents: ['monocyte'],
      stage: 'mature',
      terminal: true,
      markers: 'CD14lo CD16+ CX3CR1hi',
      description: 'Patrolling monocyte derived from classical monocytes (mouse Ly6Clo); NR4A1-dependent.',
    },
    {
      id: 'macrophage',
      label: 'Macrophage (monocyte-derived)',
      parents: ['monocyte'],
      stage: 'mature',
      terminal: true,
      iconId: 'cells.macrophage',
      markers: 'CD68+ CD163+ CD206+',
      description: 'Monocyte-derived tissue macrophage. Note: many tissue-resident macrophages (microglia, Kupffer, alveolar) are embryonically seeded from yolk-sac/fetal-liver progenitors, not shown here.',
    },
    {
      id: 'osteoclast',
      label: 'Osteoclast',
      parents: ['monocyte'],
      stage: 'mature',
      terminal: true,
      markers: 'TRAP (ACP5)+ CTSK+ CALCR+',
      description: 'Multinucleated bone-resorbing cell formed by RANKL/M-CSF-driven fusion of monocyte/macrophage precursors.',
    },

    // ───────────────────────── Dendritic cells ─────────────────────────
    {
      id: 'cdp',
      label: 'Common DC progenitor (CDP)',
      parents: ['mdp'],
      stage: 'committed',
      lineage: 'dendritic',
      markers: 'CD117lo CD115+ CD135+ CD123+',
      description: 'DC-restricted progenitor giving cDC1, cDC2 and (part of) pDC (Naik 2007; Onai 2007; Lee 2015).',
    },
    {
      id: 'pre-cdc',
      label: 'Pre-cDC',
      parents: ['cdp'],
      stage: 'precursor',
      markers: 'CD11clo CD135+ CD45RA+ CD117lo',
      description: 'Circulating committed cDC precursor (Breton 2015; See 2017).',
    },
    {
      id: 'cdc1',
      label: 'Conventional DC type 1 (cDC1)',
      parents: ['pre-cdc'],
      stage: 'mature',
      terminal: true,
      markers: 'CD141+ XCR1+ CLEC9A+',
      description: 'IRF8/BATF3-dependent cross-presenting DC. Mouse: CD8α+/CD103+ XCR1+.',
    },
    {
      id: 'cdc2',
      label: 'Conventional DC type 2 (cDC2)',
      parents: ['pre-cdc'],
      stage: 'mature',
      terminal: true,
      markers: 'CD1c+ CD11c+ SIRPα+',
      description: 'IRF4-dependent DC presenting to CD4 T cells. Mouse: CD11b+ SIRPα+.',
    },
    {
      id: 'pdc',
      label: 'Plasmacytoid DC (pDC)',
      parents: ['cdp', 'clp'],
      stage: 'mature',
      terminal: true,
      markers: 'CD123+ CD303+ CD304+ TCF4',
      description: 'Type I interferon producer; TCF4 (E2-2)-dependent. Secondary parent: lymphoid (CLP/IL7R+) origin for a substantial fraction (Rodrigues 2018; Dress 2019).',
    },
    {
      id: 'mo-dc',
      label: 'Monocyte-derived DC (moDC)',
      parents: ['monocyte'],
      stage: 'mature',
      terminal: true,
      lineage: 'dendritic',
      markers: 'CD1a+ CD11c+ CD209 (DC-SIGN)+',
      description: 'Inflammatory / in vitro GM-CSF + IL-4 derived DC.',
    },

    // ───────────────────────── B lymphoid ─────────────────────────
    {
      id: 'pro-b',
      label: 'Pro-B cell',
      parents: ['clp'],
      stage: 'committed',
      lineage: 'b-lymphoid',
      markers: 'CD34+ CD19+ CD10+ PAX5',
      description: 'EBF1/PAX5-committed; D–J then V–DJ heavy-chain rearrangement (RAG1/2, TdT). Mouse Hardy fractions B–C.',
    },
    {
      id: 'pre-b',
      label: 'Pre-B cell',
      parents: ['pro-b'],
      stage: 'precursor',
      markers: 'CD19+ CD10+ CD34− pre-BCR+',
      description: 'Cytoplasmic μ chain with surrogate light chain (VPREB1/IGLL1); light-chain rearrangement in small pre-B.',
    },
    {
      id: 'immature-b',
      label: 'Immature B cell',
      parents: ['pre-b'],
      stage: 'precursor',
      markers: 'CD19+ CD10+ IgM+ IgD−',
      description: 'Surface IgM; central tolerance (receptor editing / deletion) in marrow.',
    },
    {
      id: 'transitional-b',
      label: 'Transitional B cell (T1/T2)',
      parents: ['immature-b'],
      stage: 'precursor',
      markers: 'CD19+ CD24hi CD38hi IgM+ IgD+',
      description: 'Recent marrow emigrants in blood/spleen; BAFF-dependent selection.',
    },
    {
      id: 'naive-b',
      label: 'Mature naive B cell',
      parents: ['transitional-b'],
      stage: 'mature',
      iconId: 'cells.b-cell',
      markers: 'CD19+ CD20+ IgM+ IgD+ CD27−',
      description: 'Follicular (and marginal-zone) mature B cell. Activation yields germinal-centre B, extrafollicular plasma cells and GC-independent memory.',
    },
    {
      id: 'gc-b',
      label: 'Germinal centre B cell',
      parents: ['naive-b'],
      stage: 'mature',
      markers: 'CD19+ CD38+ CD10+ BCL6 AICDA',
      description: 'Somatic hypermutation and class-switch recombination; BCL6-dependent.',
    },
    {
      id: 'memory-b',
      label: 'Memory B cell',
      parents: ['gc-b', 'naive-b'],
      stage: 'mature',
      terminal: true,
      iconId: 'cells.b-cell',
      markers: 'CD19+ CD27+ CD38lo',
      description: 'Long-lived antigen-experienced B cell. Secondary parent: GC-independent memory from activated naive B (Weisel 2016).',
    },
    {
      id: 'plasma-cell',
      label: 'Plasma cell',
      parents: ['gc-b', 'naive-b'],
      stage: 'mature',
      terminal: true,
      markers: 'CD38hi CD138+ CD27+ CD20− PRDM1',
      description: 'Antibody-secreting cell; PRDM1 (BLIMP1)/XBP1/IRF4. Secondary parent: extrafollicular short-lived plasma cells from activated naive B.',
    },

    // ───────────────────────── T lymphoid ─────────────────────────
    {
      id: 'etp',
      label: 'Early thymic progenitor (ETP / DN1)',
      parents: ['clp', 'lmpp'],
      stage: 'committed',
      lineage: 't-lymphoid',
      markers: 'CD34+ CD7+ CD1a− CD4− CD8−',
      description: 'Thymus-seeding progenitor; Notch1 signalling commits to T lineage (TCF7, BCL11B). Secondary parent: LMPP/MPP-like thymus seeding (mouse). Mouse: Kit+ CD44+ CD25−.',
    },
    {
      id: 'dn-thymocyte',
      label: 'DN2–DN3 thymocyte',
      parents: ['etp'],
      stage: 'precursor',
      markers: 'CD7+ CD1a+ CD4− CD8− RAG1/2',
      description: 'TCRβ (or γδ) rearrangement; β-selection at DN3. Mouse: CD44+/−CD25+.',
    },
    {
      id: 'dp-thymocyte',
      label: 'Double-positive thymocyte (DP)',
      parents: ['dn-thymocyte'],
      stage: 'precursor',
      markers: 'CD4+ CD8+ TCRαβlo CD1a+',
      description: 'TCRα rearrangement; positive selection on cortical epithelium; negative selection in medulla.',
    },
    {
      id: 'cd4-sp',
      label: 'CD4 single-positive thymocyte (SP)',
      parents: ['dp-thymocyte'],
      stage: 'precursor',
      markers: 'CD4+ CD8− TCRαβ+ ZBTB7B (ThPOK)',
      description: 'MHC-II-restricted; ThPOK-driven CD4 lineage choice.',
    },
    {
      id: 'cd8-sp',
      label: 'CD8 single-positive thymocyte (SP)',
      parents: ['dp-thymocyte'],
      stage: 'precursor',
      markers: 'CD4− CD8+ TCRαβ+ RUNX3',
      description: 'MHC-I-restricted; RUNX3-driven CD8 lineage choice.',
    },
    {
      id: 'naive-cd4',
      label: 'Naive CD4 T cell',
      parents: ['cd4-sp'],
      stage: 'mature',
      iconId: 'cells.t-cell',
      markers: 'CD4+ CD45RA+ CCR7+ CD62L+',
      description: 'Recent thymic emigrant / naive helper T cell.',
    },
    {
      id: 'effector-memory-cd4',
      label: 'Effector / memory CD4 T cell',
      parents: ['naive-cd4'],
      stage: 'mature',
      terminal: true,
      iconId: 'cells.t-cell',
      markers: 'CD4+ CD45RO+ TBX21 / GATA3 / RORC / BCL6',
      description: 'Th1 / Th2 / Th17 / Tfh effector and central/effector memory subsets.',
    },
    {
      id: 'treg',
      label: 'Regulatory T cell (Treg)',
      parents: ['cd4-sp', 'naive-cd4'],
      stage: 'mature',
      terminal: true,
      iconId: 'cells.t-cell',
      markers: 'CD4+ CD25+ FOXP3+ CD127lo',
      description: 'Thymic (tTreg) from CD4 SP thymocytes; secondary parent: peripherally induced pTreg from naive CD4 T cells.',
    },
    {
      id: 'naive-cd8',
      label: 'Naive CD8 T cell',
      parents: ['cd8-sp'],
      stage: 'mature',
      iconId: 'cells.t-cell',
      markers: 'CD8+ CD45RA+ CCR7+ CD62L+',
      description: 'Naive cytotoxic T-cell precursor.',
    },
    {
      id: 'effector-memory-cd8',
      label: 'Effector / memory CD8 T cell (CTL)',
      parents: ['naive-cd8'],
      stage: 'mature',
      terminal: true,
      iconId: 'cells.t-cell',
      markers: 'CD8+ CD45RO+ GZMB PRF1',
      description: 'Cytotoxic effector and central/effector memory subsets.',
    },
    {
      id: 'gd-t',
      label: 'γδ T cell',
      parents: ['dn-thymocyte'],
      stage: 'mature',
      terminal: true,
      iconId: 'cells.t-cell',
      markers: 'TCRγδ+ CD3+ CD4− CD8−',
      description: 'Diverges at the DN2/DN3 stage via productive TCRγ/δ rearrangement.',
    },
    {
      id: 'inkt',
      label: 'Invariant NKT cell (iNKT)',
      parents: ['dp-thymocyte'],
      stage: 'mature',
      terminal: true,
      iconId: 'cells.t-cell',
      markers: 'Vα24-Jα18 TCR CD1d-restricted ZBTB16 (PLZF)',
      description: 'Selected by CD1d-lipid on DP thymocytes; PLZF-dependent innate-like T cell.',
    },

    // ───────────────────────── NK cells and innate lymphoid cells ─────────────────────────
    {
      id: 'cilp',
      label: 'Common ILC progenitor (CILP)',
      parents: ['clp'],
      stage: 'committed',
      lineage: 'nk-ilc',
      markers: 'CD34+ CD45RA+ CD7+ CD127+ ID2 NFIL3',
      description: 'ID2/NFIL3/TOX-dependent progenitor of NK cells and helper ILCs (Constantinides 2014; Lim 2017 human).',
    },
    {
      id: 'nkp',
      label: 'NK progenitor (NKP)',
      parents: ['cilp'],
      stage: 'precursor',
      markers: 'CD122 (IL2RB)+ CD7+ CD56− EOMES',
      description: 'IL-15-responsive NK-committed progenitor (Renoux 2015 human).',
    },
    {
      id: 'nk-cd56bright',
      label: 'CD56bright NK cell',
      parents: ['nkp'],
      stage: 'mature',
      markers: 'CD56bright CD16− CD94+ NKG2A+',
      description: 'Cytokine-producing, less cytotoxic NK subset; precursor of CD56dim NK (widely held linear model).',
    },
    {
      id: 'nk-cd56dim',
      label: 'CD56dim NK cell',
      parents: ['nk-cd56bright'],
      stage: 'mature',
      terminal: true,
      markers: 'CD56dim CD16+ KIR+ CD57',
      description: 'Cytotoxic, KIR-expressing mature NK subset.',
    },
    {
      id: 'ilcp',
      label: 'ILC precursor (ILCP)',
      parents: ['cilp'],
      stage: 'precursor',
      markers: 'CD127+ CD117+ CRTH2− ZBTB16 (PLZF)',
      description: 'Helper-ILC-restricted precursor (mouse CHILP/ILCP; human CD117+ ILCP, Lim 2017).',
    },
    {
      id: 'ilc1',
      label: 'Group 1 ILC (ILC1)',
      parents: ['ilcp'],
      stage: 'mature',
      terminal: true,
      markers: 'CD127+ CD117− CRTH2− TBX21 IFNG',
      description: 'T-bet-dependent IFN-γ producer.',
    },
    {
      id: 'ilc2',
      label: 'Group 2 ILC (ILC2)',
      parents: ['ilcp'],
      stage: 'mature',
      terminal: true,
      markers: 'CD127+ CRTH2+ GATA3 IL5 IL13',
      description: 'GATA3-dependent type-2 cytokine producer.',
    },
    {
      id: 'ilc3',
      label: 'Group 3 ILC / LTi (ILC3)',
      parents: ['ilcp'],
      stage: 'mature',
      terminal: true,
      markers: 'CD127+ CD117+ RORC IL22',
      description: 'RORγt-dependent IL-22/IL-17 producer; LTi cells branch earlier (from CHILP) in mouse — simplified here.',
    },
  ],

  edges: [
    { from: 'lt-hsc', to: 'lt-hsc', kind: 'self', label: 'self-renewal' },
    { from: 'erythroblast', to: 'reticulocyte', kind: 'primary', label: 'enucleation' },
    { from: 'megakaryocyte', to: 'platelet', kind: 'primary', label: 'proplatelet shedding' },
    { from: 'clp', to: 'etp', kind: 'primary', label: 'thymic seeding' },
    { from: 'dn-thymocyte', to: 'dp-thymocyte', kind: 'primary', label: 'β-selection' },
    { from: 'naive-b', to: 'gc-b', kind: 'primary', label: 'SHM / class switch' },
  ],
}
